<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="<?php echo $csrfToken; ?>" />
    <title>Krystal Framework: You're ready to start!</title>
    
    <?php foreach ($this->getPluginBag()->getStylesheets() as $path): ?>
    <link href="<?php echo $path; ?>" rel="stylesheet" />
    <?php endforeach; ?>
  </head>

  <body role="document">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
          <a class="navbar-brand" href="/">Project</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="/"><?php $this->show('Home'); ?></a></li>
            <li class="nav-item"><a class="nav-link" href="<?= $this->url('Scaffold:Scaffold@indexAction'); ?>"><?php $this->show('Code generator'); ?></a></li>
            <li class="nav-item"><a class="nav-link" href="<?php echo $this->url('Site:Contact@indexAction'); ?>"><?php $this->show('Contact'); ?></a></li>
            <?php if (!$isLoggedIn): ?>
            <li class="nav-item"><a class="nav-link" href="<?php echo $this->url('Site:Auth@indexAction'); ?>"><?php $this->show('Login'); ?></a></li>
            <?php else: ?>
            <li class="nav-item"><a class="nav-link" href="<?php echo $this->url('Site:Profile@indexAction'); ?>"><?php $this->show('My profile'); ?></a></li>
            <li class="nav-item"><a class="nav-link" href="<?php echo $this->url('Site:Auth@logoutAction'); ?>"><?php $this->show('Logout'); ?></a></li>
            <?php endif; ?>
            </ul>
          </div>
        </div>
    </nav>

    <div class="container" role="main">
        <?= $this->widget(new \Krystal\Widget\Breadcrumbs\BreadcrumbWidget); ?>

        <?php if ($flashBag->has('success')): ?>
        <div class="alert alert-success" role="alert"><i class="glyphicon glyphicon-ok"></i> <?php echo $flashBag->get('success'); ?></div>
        <?php endif; ?>

        <?php if ($flashBag->has('warning')): ?>
        <div class="alert alert-warning" role="alert"><?php echo $flashBag->get('warning'); ?></div>
        <?php endif; ?>

        <?php echo $fragment; ?>
    </div>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <?php foreach ($this->getPluginBag()->getScripts() as $script): ?>
    <script src="<?php echo $script; ?>"></script>
    <?php endforeach;?>
  </body>
</html>