
<h2 class="page-header"><?php $this->show('Contact us'); ?></h2>

<form method="POST" class="form-horizontal" autocomplete="off">
  <fieldset>
    <?= $this->field('Email')->text('email', null, ['class' => 'form-control', 'placeholder' => $this->translate('Type your email')]); ?>
    <?= $this->field('Subject')->text('subject', null, ['class' => 'form-control', 'placeholder' => $this->translate('Type the subject of your email')]); ?>
    <?= $this->field('Message')->textarea('message', null, ['class' => 'form-control', 'rows' => 3, 'placeholder' => $this->translate('Type your message')]); ?>

    <div class="form-group">
        <label for="inputCaptcha" class="col-lg-2"></label>
        <div class="col-lg-10">
            <a href="#" title="<?php $this->show('Click to refresh'); ?>" data-captcha="button-refresh"><img data-captcha="image" src="<?= $this->url('Site:Site@captchaAction', null); ?>" /></a>
        </div>
    </div>

    <?= $this->field()->text('captcha', null, ['class' => 'form-control', 'placeholder' => $this->translate('Prove that you are not a bot')]); ?>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" data-button="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>