<?php

use Krystal\Form\Element;

?>

<div class="row">
    <div class="col-lg-6">
        <form method="POST">
          <fieldset>
            <legend><?php $this->show('Update your profile'); ?></legend>

            <div class="form-group">
              <label><?php $this->show('Your name'); ?></label>
              <?= Element::textarea('name', $user['name'], array('class' => 'form-control')); ?>
            </div>

            <div class="form-group">
              <label><?php $this->show('Birthday'); ?></label>
              <?= Element::date('birthday', $user['birthday'], array('class' => 'form-control')); ?>
            </div>

            <div class="form-group">
              <label><?php $this->show('Your email'); ?></label>
              <?= Element::email('email', $user['email'], array('class' => 'form-control')); ?>
            </div>

            <div class="form-group">
              <label><?php $this->show('Gender'); ?></label>
              <?= Element::select('gender', $genders, $user['gender'], array('class' => 'form-control')); ?>
            </div>

            <div class="form-group">
              <label><?php $this->show('About yourself'); ?></label>
              <?= Element::textarea('about', $user['about'], array('class' => 'form-control', 'rows' => 3)); ?>
            </div>

            <div class="form-group">
              <label><?php $this->show('Path to avatar'); ?></label>
              <?= Element::text('avatar', $user['avatar'], array('class' => 'form-control')); ?>
            </div>
          </fieldset>

          <fieldset>
            <legend><?php $this->show('Change password'); ?></legend>

            <div class="form-group">
              <label><?php $this->show('New password'); ?></label>
              <?= Element::password('password', null, array('class' => 'form-control', 'placeholder' => $this->translate('Leave blank if you do not want to change your password'))); ?>
            </div>

            <p>
                <a href="<?= $this->url('User:Profile@destroyAction'); ?>"><?php $this->show('Destroy your profile?'); ?></a>
            </p>

            <button type="submit" class="btn btn-primary"><?php $this->show('Submit'); ?></button>
          </fieldset>
        </form>
    </div>
</div>