<?php

use Krystal\Form\Element;

?>

<h2 class="page-header"><?php $this->show('Password recovery'); ?></h2>

<form class="form-horizontal" autocomplete="off" action="<?= $this->url('Site:Recovery@submitAction'); ?>">
  <fieldset class="col-lg-5">
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
      <div class="col-lg-10">
        <?= Element::email('email', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type your email'))); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 pull-right">
        <button type="submit" data-button="submit" class="btn btn-success"> <?php $this->show('Proceed'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
