<?php

use Krystal\Form\Element;

?>

<h2 class="page-header"><?php $this->show('Password recovery'); ?></h2>

<?php $this->loadPartial('breadcrumbs'); ?>

<?php if ($flashBag->has('success')): ?>
<div class="alert alert-success" role="alert"><i class="glyphicon glyphicon-ok"></i> <?php echo $flashBag->get('success'); ?></div>
<?php endif; ?>

<form class="form-horizontal" autocomplete="off" action="<?= $this->url('Site:Recovery@updateAction'); ?>">
  <fieldset class="col-lg-5">
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label"><?php $this->show('Password'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('password', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type your new password'))); ?>
        <?= Element::hidden('token', $token); ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 pull-right">
        <button type="submit" data-button="submit" class="btn btn-success"> <?php $this->show('Update'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
